require 'generator/logs/simple_logs'
require 'generator/logs/simple_exponents'
require 'generator/logs/advanced_logs'
require 'generator/logs/advanced_exponents'
require 'generator/logs/arbitrary_base_logs'
require 'generator/logs/arbitrary_base_exponents'