require 'generator/powers/basic_squares_and_roots'
require 'generator/powers/basic_cubes_and_roots'
require 'generator/powers/compound_squares'
require 'generator/powers/compound_roots'
require 'generator/powers/basic_powers'