require 'generator/trig/all'
require 'generator/trig/cos'
require 'generator/trig/sin'
require 'generator/trig/tan'
require 'generator/trig/sec'
require 'generator/trig/csc'
require 'generator/trig/cot'
require 'generator/trig/inverse'
require 'generator/trig/secant'

require 'generator/trig/angle_conversions'
require 'generator/trig/polar'